package org.itson.disenosw.guis;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Esta clase representa la vista de inicio de sesión en la interfaz gráfica del
 * banco. Permite a los usuarios iniciar sesión proporcionando su nombre de
 * usuario y contraseña.
 */
public class PanelPagoExitoPuntos extends javax.swing.JPanel {

    private FramePrincipal framePrincipal;

    /**
     * Constructor de la clase VistaInicioSesion.
     *
     * @param framePrincipal La framePrincipal principal de la aplicación.
     */
    public PanelPagoExitoPuntos(FramePrincipal framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();

    }

    public PanelPagoExitoPuntos(FramePrincipal framePrincipal, Integer puntosGenerados, String claveRecoger) {
        try {
            this.framePrincipal = framePrincipal;
            initComponents();

            lblPuntosGenerados.setText(puntosGenerados.toString() + " puntos");
            lblClaveRecoger.setText(claveRecoger);
            lblNumPedido.setText(Integer.toString(framePrincipal.getNumPedido() + 1));
            framePrincipal.setIdPedido(framePrincipal.getIdPedido() + 1);
        } catch (Exception ex) {
            Logger.getLogger(PanelPagoExitoPuntos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        lblPuntosGenerados = new javax.swing.JLabel();
        lblClaveRecoger = new javax.swing.JLabel();
        lblNumPedido = new javax.swing.JLabel();
        btnRegresarMenu = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 800));
        setMinimumSize(new java.awt.Dimension(400, 800));
        setPreferredSize(new java.awt.Dimension(400, 800));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 65, 65));

        lblPuntosGenerados.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblPuntosGenerados.setText("label");
        add(lblPuntosGenerados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 230, 30));

        lblClaveRecoger.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblClaveRecoger.setText("label");
        add(lblClaveRecoger, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 230, 30));

        lblNumPedido.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblNumPedido.setText("label");
        add(lblNumPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 230, 30));

        btnRegresarMenu.setBorder(null);
        btnRegresarMenu.setContentAreaFilled(false);
        btnRegresarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuActionPerformed(evt);
            }
        });
        add(btnRegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 170, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/panelPagoExitoPuntos.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuActionPerformed
        framePrincipal.cambiarVistaMenu();
    }//GEN-LAST:event_btnRegresarMenuActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        framePrincipal.cambiarVistaMenu();
    }//GEN-LAST:event_btnMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegresarMenu;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel lblClaveRecoger;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JLabel lblPuntosGenerados;
    // End of variables declaration//GEN-END:variables
}
